module.exports = {
  apps: [
    {
      name: "pusaka-monitor",
      script: "C:\\Users\\LENOVO\\webapp\\pusaka-monitor\\pusaka-monitor.exe",
      cwd: "C:\\Users\\LENOVO\\webapp\\pusaka-monitor",
      exec_mode: "fork",
      interpreter: "none",
      windowsHide: true,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      min_uptime: "10s",
      env: {
        PORT: "8091",
        GIN_MODE: "release",
        DB_PATH: "data/presensi.db",
        JWT_SECRET: "dZBbH0A6UEL-pp283YHyAJ0b-E1p0pfqbMclZkINPVzSbq08QAMDSGpB1ErzJNqP",
        SUPERADMIN_USERNAME: "admin",
        SUPERADMIN_PASSWORD: "admin123",
        ENCRYPTION_KEY: "dZBbH0A6UEL-pp283YHyAJ0b-E1p0pfqbMclZkINPVzSbq08QAMDSGpB1ErzJNqP",
      },
      error_file: "C:\\Users\\LENOVO\\webapp\\pusaka-monitor\\logs\\error.log",
      out_file: "C:\\Users\\LENOVO\\webapp\\pusaka-monitor\\logs\\out.log",
      log_file: "C:\\Users\\LENOVO\\webapp\\pusaka-monitor\\logs\\combined.log",
      merge_logs: true,
      time: true,
    },
  ],
};
