// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// Halaman Profil — self-reset password
func ProfilPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = Sidebar("profil").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, " <div class=\"lg:pl-56 min-h-screen pb-20 lg:pb-0\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = Topbar("Profil", "").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<main class=\"p-4 page-enter\"><!-- Akun Saya --><div class=\"bg-white rounded-xl border border-gray-200 shadow-sm mb-4\"><div class=\"px-4 py-2.5 border-b border-gray-200 text-sm font-semibold text-gray-700\"><i class=\"fa-solid fa-circle-user mr-1\"></i> Akun Saya</div><div class=\"p-4 space-y-2\"><div class=\"flex justify-between text-sm\"><span class=\"text-gray-500\">Username</span> <span class=\"font-semibold text-gray-900\" id=\"meUser\">-</span></div><div class=\"flex justify-between text-sm\"><span class=\"text-gray-500\">Role</span> <span class=\"text-gray-900\" id=\"meRole\">-</span></div></div></div><!-- Ganti Password --><div class=\"bg-white rounded-xl border border-gray-200 shadow-sm\"><div class=\"px-4 py-2.5 border-b border-gray-200 text-sm font-semibold text-gray-700\"><i class=\"fa-solid fa-key mr-1\"></i> Ganti Password</div><div class=\"p-4 space-y-3\"><div><label class=\"block text-sm font-medium text-gray-700 mb-1\">Password Lama</label> <input type=\"password\" id=\"oldPwd\" class=\"w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none\" placeholder=\"Password saat ini\"></div><div><label class=\"block text-sm font-medium text-gray-700 mb-1\">Password Baru</label> <input type=\"password\" id=\"newPwd\" class=\"w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none\" placeholder=\"Minimal 4 karakter\"></div><button onclick=\"resetOwn()\" class=\"w-full px-4 py-2.5 bg-blue-600 hover:bg-blue-700 text-white rounded-lg text-sm font-medium transition-colors\"><i class=\"fa-solid fa-check mr-1\"></i> Simpan Password Baru</button></div></div></main></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = BottomNav("profil").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, " <script>\n\t\t\tasync function loadMe() {\n\t\t\t\tconst res = await fetch('/api/auth/me');\n\t\t\t\tconst d = await res.json();\n\t\t\t\tif (d.success) {\n\t\t\t\t\tdocument.getElementById('meUser').textContent = d.data.username || '-';\n\t\t\t\t\tdocument.getElementById('meRole').textContent = d.data.role || '-';\n\t\t\t\t}\n\t\t\t}\n\t\t\tasync function resetOwn() {\n\t\t\t\tconst oldP = document.getElementById('oldPwd').value;\n\t\t\t\tconst newP = document.getElementById('newPwd').value;\n\t\t\t\tif (!oldP || !newP) { showToast('Isi password lama & baru','danger'); return; }\n\t\t\t\tconst res = await fetch('/api/me/reset-password', {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({old_password:oldP,new_password:newP})});\n\t\t\t\tconst d = await res.json();\n\t\t\t\tif (d.success) { showToast('Password berhasil diubah'); document.getElementById('oldPwd').value=''; document.getElementById('newPwd').value=''; }\n\t\t\t\telse showToast(d.error||'Gagal','danger');\n\t\t\t}\n\t\t\tloadMe();\n\t\t</script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("Profil", "", "").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// Halaman User Management (superadmin) — list user + reset password
func UsersPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var4 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = Sidebar("users").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, " <div class=\"lg:pl-56 min-h-screen pb-20 lg:pb-0\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = Topbar("User Management", "").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<main class=\"p-4 page-enter\"><div class=\"bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden\"><div class=\"px-4 py-2.5 border-b border-gray-200 text-sm font-semibold text-gray-700\"><i class=\"fa-solid fa-users mr-1\"></i> Daftar User</div><div class=\"overflow-x-auto\"><table class=\"w-full text-sm\"><thead class=\"bg-gray-50 text-gray-500 text-xs uppercase\"><tr><th class=\"px-4 py-2 text-left\">Username</th><th class=\"px-4 py-2 text-center\">Role</th><th class=\"px-4 py-2 text-left\">Instansi</th><th class=\"px-4 py-2 text-right\">Aksi</th></tr></thead> <tbody id=\"userTable\" class=\"divide-y divide-gray-100\"><tr><td colspan=\"4\" class=\"px-4 py-6 text-center text-gray-400 text-sm\">Memuat...</td></tr></tbody></table></div></div></main></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = BottomNav("users").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, " <script>\n\t\t\tasync function loadUsers() {\n\t\t\t\tconst res = await fetch('/api/superadmin/users');\n\t\t\t\tconst d = await res.json();\n\t\t\t\tif (!d.success) return;\n\t\t\t\tconst tb = document.getElementById('userTable');\n\t\t\t\ttb.innerHTML = d.data.map(u => `<tr class=\"hover:bg-gray-50\">\n\t\t\t\t\t<td class=\"px-4 py-2 font-medium text-gray-900\">${u.username}</td>\n\t\t\t\t\t<td class=\"px-4 py-2 text-center\"><span class=\"inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium ${u.role==='superadmin'?'bg-red-100 text-red-700':'bg-gray-100 text-gray-600'}\">${u.role}</span></td>\n\t\t\t\t\t<td class=\"px-4 py-2 text-gray-500 text-xs\">${u.instansi_nama || '-'}</td>\n\t\t\t\t\t<td class=\"px-4 py-2 text-right\">\n\t\t\t\t\t\t<button onclick=\"resetUser('${u.id}','${u.username}')\" class=\"px-3 py-1 border border-gray-200 rounded-lg text-xs font-medium hover:bg-gray-50 transition-colors\">\n\t\t\t\t\t\t\t<i class=\"fa-solid fa-key mr-1\"></i>Reset\n\t\t\t\t\t\t</button>\n\t\t\t\t\t</td>\n\t\t\t\t</tr>`).join('');\n\t\t\t}\n\t\t\tfunction resetUser(id, username) {\n\t\t\t\tconst pwd = prompt('Password baru untuk ' + username + ' (minimal 4 karakter):');\n\t\t\t\tif (!pwd || pwd.length < 4) { if (pwd!==null) showToast('Minimal 4 karakter','danger'); return; }\n\t\t\t\tfetch('/api/superadmin/users/'+id+'/reset-password', {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({new_password:pwd})})\n\t\t\t\t.then(r=>r.json()).then(d => { if (d.success) showToast('Password '+username+' direset'); else showToast(d.error||'Gagal','danger'); });\n\t\t\t}\n\t\t\tloadUsers();\n\t\t</script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("User Management", "", "").Render(templ.WithChildren(ctx, templ_7745c5c3_Var4), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
