// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// Halaman Profil — self-reset password
func ProfilPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = Sidebar("profil").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, " <div class=\"main-content\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = Topbar("Profil").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"content\"><div class=\"card mb-2\"><div class=\"card-header py-2\"><i class=\"bi bi-person-circle\"></i> Akun Saya</div><div class=\"card-body py-2\"><p class=\"mb-1\"><strong>Username:</strong> <span id=\"meUser\">-</span></p><p class=\"mb-0\"><strong>Role:</strong> <span id=\"meRole\">-</span></p></div></div><div class=\"card\"><div class=\"card-header py-2\"><i class=\"bi bi-key\"></i> Ganti Password</div><div class=\"card-body\"><div class=\"mb-3\"><label class=\"form-label fw-semibold\">Password Lama</label> <input type=\"password\" class=\"form-control\" id=\"oldPwd\" placeholder=\"Password saat ini\"></div><div class=\"mb-3\"><label class=\"form-label fw-semibold\">Password Baru</label> <input type=\"password\" class=\"form-control\" id=\"newPwd\" placeholder=\"Minimal 4 karakter\"></div><button class=\"btn btn-primary w-100\" onclick=\"resetOwn()\"><i class=\"bi bi-check-lg\"></i> Simpan Password Baru</button></div></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = BottomNav("profil").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, " <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script> <script>\n\t\t\tasync function loadMe() {\n\t\t\t\tconst res = await fetch('/api/auth/me');\n\t\t\t\tconst d = await res.json();\n\t\t\t\tif (d.success) {\n\t\t\t\t\tdocument.getElementById('meUser').textContent = d.data.username || '-';\n\t\t\t\t\tdocument.getElementById('meRole').textContent = d.data.role || '-';\n\t\t\t\t}\n\t\t\t}\n\t\t\tasync function resetOwn() {\n\t\t\t\tconst oldP = document.getElementById('oldPwd').value;\n\t\t\t\tconst newP = document.getElementById('newPwd').value;\n\t\t\t\tif (!oldP || !newP) { showToast('Isi password lama & baru', 'danger'); return; }\n\t\t\t\tconst res = await fetch('/api/me/reset-password', {\n\t\t\t\t\tmethod: 'POST',\n\t\t\t\t\theaders: {'Content-Type': 'application/json'},\n\t\t\t\t\tbody: JSON.stringify({ old_password: oldP, new_password: newP })\n\t\t\t\t});\n\t\t\t\tconst d = await res.json();\n\t\t\t\tif (d.success) {\n\t\t\t\t\tshowToast('Password berhasil diubah');\n\t\t\t\t\tdocument.getElementById('oldPwd').value = '';\n\t\t\t\t\tdocument.getElementById('newPwd').value = '';\n\t\t\t\t} else {\n\t\t\t\t\tshowToast(d.error || 'Gagal', 'danger');\n\t\t\t\t}\n\t\t\t}\n\t\t\tloadMe();\n\t\t</script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("Profil", "", "").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// Halaman User Management (superadmin) — list user + reset password
func UsersPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var4 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = Sidebar("users").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, " <div class=\"main-content\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = Topbar("User Management").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<div class=\"content\"><div class=\"card\"><div class=\"card-header py-2\"><i class=\"bi bi-people\"></i> Daftar User</div><div class=\"table-responsive\"><table class=\"table table-hover mb-0\"><thead><tr><th>Username</th><th>Role</th><th>Instansi</th><th></th></tr></thead> <tbody id=\"userTable\"><tr><td colspan=\"4\" class=\"text-center text-muted py-4\">Memuat...</td></tr></tbody></table></div></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = BottomNav("users").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, " <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script> <script>\n\t\t\tlet allUsers = [];\n\t\t\tasync function loadUsers() {\n\t\t\t\tconst res = await fetch('/api/superadmin/users');\n\t\t\t\tconst d = await res.json();\n\t\t\t\tif (!d.success) return;\n\t\t\t\tallUsers = d.data;\n\t\t\t\tconst tb = document.getElementById('userTable');\n\t\t\t\ttb.innerHTML = d.data.map(u => `\n\t\t\t\t\t<tr>\n\t\t\t\t\t\t<td>${u.username}</td>\n\t\t\t\t\t\t<td><span class=\"badge ${u.role==='superadmin'?'bg-danger':'bg-primary'}\">${u.role}</span></td>\n\t\t\t\t\t\t<td><small class=\"text-muted\">${u.instansi_nama || '-'}</small></td>\n\t\t\t\t\t\t<td class=\"text-end\">\n\t\t\t\t\t\t\t<button class=\"btn btn-sm btn-outline-warning\" onclick=\"resetUser('${u.id}','${u.username}')\"><i class=\"bi bi-key\"></i> Reset</button>\n\t\t\t\t\t\t</td>\n\t\t\t\t\t</tr>\n\t\t\t\t`).join('');\n\t\t\t}\n\t\t\tfunction resetUser(id, username) {\n\t\t\t\tconst pwd = prompt('Password baru untuk ' + username + ' (minimal 4 karakter):');\n\t\t\t\tif (!pwd || pwd.length < 4) { if (pwd!==null) showToast('Minimal 4 karakter', 'danger'); return; }\n\t\t\t\tfetch('/api/superadmin/users/' + id + '/reset-password', {\n\t\t\t\t\tmethod: 'POST',\n\t\t\t\t\theaders: {'Content-Type': 'application/json'},\n\t\t\t\t\tbody: JSON.stringify({ new_password: pwd })\n\t\t\t\t}).then(r => r.json()).then(d => {\n\t\t\t\t\tif (d.success) showToast('Password ' + username + ' direset');\n\t\t\t\t\telse showToast(d.error || 'Gagal', 'danger');\n\t\t\t\t});\n\t\t\t}\n\t\t\tloadUsers();\n\t\t</script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("User Management", "", "").Render(templ.WithChildren(ctx, templ_7745c5c3_Var4), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
