// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func SettingsPage(username string, role string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = Sidebar("settings").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, " <div class=\"main-content\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = Topbar("Pengaturan").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"content\"><!-- Info Akun --><div class=\"card mb-4\"><div class=\"card-header\"><i class=\"bi bi-person-badge\"></i> Info Akun</div><div class=\"card-body\"><div class=\"row mb-2\"><div class=\"col-4 text-muted\">Username</div><div class=\"col-8 fw-semibold\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(username)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/settings.templ`, Line: 15, Col: 48}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div></div><div class=\"row mb-2\"><div class=\"col-4 text-muted\">Role</div><div class=\"col-8\"><span class=\"badge bg-primary\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(role)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/settings.templ`, Line: 19, Col: 63}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</span></div></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if role == "superadmin" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<!-- Super Admin Menu --> <div class=\"card mb-2\"><div class=\"card-header\"><i class=\"bi bi-shield-lock\"></i> Super Admin</div><div class=\"card-body\"><a href=\"/approval\" class=\"btn btn-outline-primary w-100 mb-2\"><i class=\"bi bi-check-circle\"></i> Kelola Pendaftaran</a> <a href=\"/pegawai\" class=\"btn btn-outline-secondary w-100\"><i class=\"bi bi-people\"></i> Kelola Pegawai</a></div></div><!-- Worker Concurrency --> <div class=\"card mb-2\"><div class=\"card-header\"><i class=\"bi bi-cpu\"></i> Worker Scrape</div><div class=\"card-body\"><label class=\"form-label fw-semibold\">Jumlah Worker Paralel</label><div class=\"d-flex gap-2\"><input type=\"number\" min=\"1\" max=\"100\" class=\"form-control form-control-sm\" id=\"concInput\" value=\"8\"> <button class=\"btn btn-success btn-sm\" onclick=\"saveConc()\">Simpan</button></div><small class=\"text-muted\">Makin tinggi makin cepat, tapi hati-hati rate-limit Pusaka (max 60 req/jam/akun).</small></div></div><!-- Import Pegawai --> <div class=\"card mb-2\"><div class=\"card-header\"><i class=\"bi bi-upload\"></i> Import Pegawai</div><div class=\"card-body\"><input type=\"file\" class=\"form-control form-control-sm mb-2\" id=\"pegawaiFile\" accept=\".json\"> <button class=\"btn btn-primary btn-sm w-100\" onclick=\"importPegawai()\"><i class=\"bi bi-cloud-upload\"></i> Import dari JSON</button></div></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = BottomNav("settings").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, " <script>\n\t\t\t// Load concurrency saat page dibuka\n\t\t\t(async () => {\n\t\t\t\ttry {\n\t\t\t\t\tconst res = await fetch('/api/admin/concurrency');\n\t\t\t\t\tconst d = await res.json();\n\t\t\t\t\tif (d.success) document.getElementById('concInput').value = d.data.concurrency;\n\t\t\t\t} catch {}\n\t\t\t})();\n\n\t\t\tasync function saveConc() {\n\t\t\t\tconst n = parseInt(document.getElementById('concInput').value) || 1;\n\t\t\t\tconst res = await fetch('/api/admin/concurrency', {\n\t\t\t\t\tmethod: 'POST',\n\t\t\t\t\theaders: {'Content-Type': 'application/json'},\n\t\t\t\t\tbody: JSON.stringify({concurrency: n})\n\t\t\t\t});\n\t\t\t\tconst d = await res.json();\n\t\t\t\tif (d.success) showToast('Worker diatur ke ' + n);\n\t\t\t\telse showToast(d.error || 'Gagal', 'danger');\n\t\t\t}\n\n\t\t\tasync function importPegawai() {\n\t\t\t\tconst fileInput = document.getElementById('pegawaiFile');\n\t\t\t\tif (!fileInput.files.length) { showToast('Pilih file JSON dulu', 'warning'); return; }\n\t\t\t\tconst formData = new FormData();\n\t\t\t\tformData.append('file', fileInput.files[0]);\n\t\t\t\tconst res = await fetch('/api/admin/import-pegawai', { method: 'POST', body: formData });\n\t\t\t\tconst d = await res.json();\n\t\t\t\tif (d.success) showToast('Import: ' + d.data.imported + ' pegawai, ' + d.data.skipped + ' skip');\n\t\t\t\telse showToast(d.error || 'Gagal', 'danger');\n\t\t\t}\n\t\t</script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("Pengaturan", username, role).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
